// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ParkingControl.Data.DataContext;

#nullable disable

namespace ParkingControl.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230212021423_Inicial")]
    partial class Inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.13");

            modelBuilder.Entity("ParkingControl.Domain.Contexts.PargingSpots.Entities.ParkingSpot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CarEntryTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("col_tempo_entrada_veiculo");

                    b.Property<DateTime>("CarLeaveTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("col_tempo_saida_veiculo");

                    b.Property<string>("LicensePlate")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("col_placa_veiculo");

                    b.Property<int>("ParkingSpotStatus")
                        .HasColumnType("INTEGER")
                        .HasColumnName("col_status_vaga");

                    b.Property<decimal>("PriceOfParking")
                        .HasColumnType("time")
                        .HasColumnName("col_preco_estacionamento");

                    b.Property<TimeSpan>("TimeOfParking")
                        .HasColumnType("time")
                        .HasColumnName("col_tempo_total_estacionamento");

                    b.HasKey("Id");

                    b.ToTable("tb_vaga_estacionamento", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
